In [1]:
import pandas as pd
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

data = pd.read_csv('.\\data\\temp.csv')
del data['label']

#print(data.to_numpy())
tt = data.to_numpy()
#pd.reshape(data,shape=[None,28,28,1])
#print(tt)

asd = tt.reshape(-1,28,28,1)
asd = data.iloc[0:10+5]
#print(asd)

asd = np.array([[1,  2,3,  4,5,6,7,8,9,0 ],
                [9,547,347,9,3,2,6,7,3,10]])

#print(tf.argmax(ww,1))


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    ww = tf.constant(asd)
    ww = tf.argmax(ww,1)
    #sess.run(aa)
    print(ww.eval())

#tf.equal(tf.argmax(ww,1))

Instructions for updating:
non-resource variables are not supported in the long term
[8 1]


In [2]:
W = tf.Variable(tf.constant([[2.2,2],[1,1]]))
X = tf.placeholder(shape=[2,2], dtype=tf.float32)
Y = tf.placeholder(shape=[2,2], dtype=tf.float32)
B = [[3],[4]]

output = tf.matmul(X,W)+B

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    tt = sess.run(output,feed_dict = {X:[[1,0],[4,5]], Y : [[3,3],[4,5]]})
    
    a = np.array([[3,3],[4,5],[6,3]])
    b = np.array([[3,3],[4,5],[6,7]])
    print(tf.argmax(a,1).eval(),tf.argmax(b,1).eval())
    kk = tf.equal(tf.argmax(a,1).eval(),tf.argmax(b,1))
    vv = tf.reduce_mean(tf.cast(kk,dtype=tf.float32))
    
    print(vv.eval())
    #print(tt, kk.eval(),tf.argmax(tt,1).eval(),tf.argmax([[3,3],[4,5]],1).eval())
    
                

[0 1 0] [0 1 1]
0.6666667


In [12]:
value = np.array([[10,20,30,40],[20,20,30,40],[30,20,30,40],[40,20,30,40],[50,20,30,40]])
#value = np.divide(value,7)
#value = value.reshape(2,2)
print(value.shape[0])
print(value)

5
[[10 20 30 40]
 [20 20 30 40]
 [30 20 30 40]
 [40 20 30 40]
 [50 20 30 40]]


In [13]:
print(value[1:4])

[[20 20 30 40]
 [30 20 30 40]
 [40 20 30 40]]


In [15]:
qq = [i in range]

temp = np.hstack(value)
print(temp)

#np.savetxt('my.txt',value,fmt='%d',delimiter='\n')

SyntaxError: invalid syntax (<ipython-input-15-2cd052ca7ca2>, line 1)